### ISSUE TITLE
Curios Unequipping From Player

### ISSUE THREAD

**Issue by Ghaelin** [Orangejewce92/rereskillable#2]
MC Update : 1.20.1
Mod Version : 2.2.0

Description : As per the title, curios (from mods that add such items) are automatically unequipped from the player even though the config file doesn't mention them / they do not have an appropriate skill level requirement. Curiously - you can still equip them in creative and keep them equipped but as soon as you attempt to either take them off & put them back on while switched to survival it won't allow you do that.

Recreate : To simply recreate the issue equip a curio (such as one from Enigmatic Legacy) while in survival mode and the item will unequip. 

![Screenshot 2024-07-21 025641](https://github.com/user-attachments/assets/97f971d0-99ed-46d6-839a-66a0ab8b2368)

When the mod is disabled this issue ceases to continue and curios can be freely equipped / unequipped while in both creative and survival.

**Comment by Orangejewce92** [comment]
i will look into it!

**Comment by Orangejewce92** [comment]
fixed. uploading new version. also might need to regen config there was a typo in Defense was set to defence. after correcting the code it threw errors for me.

**Comment by Orangejewce92** [comment]
Curios items are working the way they are intended to work in newest version for 1.20.1
