### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by Fessssy** [Orangejewce92/rereskillable#3]
This is my config. Sorry if this isnt how Im supposed to send it, its my first tome doing this lol. The crash report says its a misplaced " but ive skimmed it and cant seem to find it

#Disable wool drops to force the player to get shears.
disableWoolDrops = true
#Reset all skills to 1 when a player dies.
deathSkillReset = false
#Starting cost of upgrading to level 2, in levels.
#Range: 0 ~ 10
startingCost = 2
#Amount of levels added to the cost with each upgrade (use 0 for constant cost).
#Range: 0 ~ 10
costIncrease = 1
#Maximum level each skill can be upgraded to.
#Range: 2 ~ 100
maximumLevel = 32
#List of item and block skill requirements.
#Format: mod:id skill:level
#Valid skills: attack, defense, mining, gathering, farming, building, agility, magic (plus any aliases defined in skillAliases)
skillLocks = ["minecraft:iron_sword attack:5", "minecraft:iron_shovel gathering:5", "minecraft:iron_pickaxe mining:5", "minecraft:iron_axe gathering:5", "minecraft:iron_hoe farming:5", "minecraft:iron_helmet defense:5", "minecraft:iron_chestplate defense:5", "minecraft:iron_leggings defense:5", "minecraft:iron_boots defense:5", "minecraft:diamond_sword attack:15", "minecraft:diamond_shovel gathering:15", "minecraft:diamond_pickaxe mining:15", "minecraft:diamond_axe gathering:15", "minecraft:diamond_hoe farming:15", "minecraft:diamond_helmet defense:15", "minecraft:diamond_chestplate defense:15", "minecraft:diamond_leggings defense:15", "minecraft:diamond_boots defense:15", "minecraft:netherite_sword attack:30", "minecraft:netherite_shovel gathering:30", "minecraft:netherite_pickaxe mining:30", "minecraft:netherite_axe gathering:30", "minecraft:netherite_hoe farming:30", "minecraft:netherite_helmet defense:30", "minecraft:netherite_chestplate defense:30", "minecraft:netherite_leggings defense:30", "minecraft:netherite_boots defense:30", "minecraft:fishing_rod gathering:5", "minecraft:shears gathering:5", "minecraft:lead farming:5", "minecraft:bow attack:5 agility:3", "minecraft:turtle_helmet defense:10", "minecraft:shield defense:5", "minecraft:crossbow attack:5 agility:5", "minecraft:trident attack:15 agility:10", "minecraft:golden_apple magic:5", "minecraft:enchanted_golden_apple magic:10", "minecraft:ender_pearl magic:5", "minecraft:ender_eye magic:10", "minecraft:piston building:5", "minecraft:sticky_piston building:10", "minecraft:tnt building:5", "minecraft:ender_chest magic:15", "minecraft:enchanting_table magic:10", "minecraft:anvil building:5", "minecraft:chipped_anvil building:5", "minecraft:damaged_anvil building:5", "minecraft:smithing_table building:10", "minecraft:end_crystal magic:20", "minecraft:boat agility:5", "minecraft:minecart agility:10", "minecraft:elytra agility:20", "minecraft:horse agility:10", "minecraft:donkey agility:10", "minecraft:mule agility:10", "minecraft:strider agility:15", "exocraft:reinforced_iron_helmet defense:15", "exocraft:reinforced_iron_chestplate defense:15", "exocraft:reinforced_iron_leggings defense:15", "exocraft:reinforced_iron_boots defense:15", "exocraft:atlas_helmet defense:15", "exocraft:atlas_chestplate defense:15", "exocraft:atlas_leggings defense:15", "exocraft:atlas_boots defense:15", "exocraft:legion_helmet defense:15" "exocraft:legion_chestplate defense:15", "exocraft:legion_leggings defense:15", "exocraft:legion_boots defense:15", "exocraft:stryder_helmet defense:15", "exocraft:stryder_chestplate defense:15", "exocraft:stryder_leggings defense:15", "exocraft:stryder_boots defense:15", "exocraft:ogre_helmet defense:15", "exocraft:ogre_chestplate defense:15", "exocraft:ogre_leggings defense:15", "exocraft:ogre_boots defense:15", "exocraft:ion_helmet defense:15", "exocraft:ion_chestplate defense:15", "exocraft:ion_leggings defense:15", "exocraft:ion_boots defense:15", "immersive_armors:bone_helmet defense:3", "immersive_armors:bone_chestplate defense:3", "immersive_armors:bone_leggings defense:3", "immersive_armors:bone_boots defense:3", "immersive_armors:wither_helmet defense:3", "immersive_armors:wither_chestplate defense:3", "immersive_armors:wither_leggings defense:3", "immersive_armors:wither_boots defense:3", "immersive_armors:warrior_helmet defense:5", "immersive_armors:warrior_chestplate defense:5", "immersive_armors:warrior_leggings defense:5", "immersive_armors:warrior_boots defense:5", "immersive_armors:heavy_helmet defense:6", "immersive_armors:heavy_chesplate defense:6", "immersive_armors:heavy_leggings defense:6", "immersive_armors:heavy_boots defense:6", "immersive_armors:robe_helmet defense:3", "immersive_armors:robe_helmet defense:3", "immersive_armors:robe_leggings defense:3", "immersive_armors:robe_boots defense:3", "immersive_armors:slime_helmet defense:5", "immersive_armors:slime_chestplate defense:5", "immersive_armors:slime_leggings defense:5", "immersive_armors:slime_boots defense:5", "immersive_armors:divine_helmet defense:5", "immersive_armors:divine_chestplate defense:7", "immersive_armors:divine_leggings defense:5", "immersive_armors:divine_boots defense:5", "immersive_armors:prismarine_helmet defense:6", "immersive_armors:prismarine_chestplate defense:8", "immersive_armors:prismarine_leggings defense:6", "immersive_armors:prismarine_boots defense:6", "immersive_armors:wooden_helmet defense:2", "immersive_armors:wooden_chestplate defense:2", "immersive_armors:wooden_leggings defense:2", "immersive_armors:wooden_boots defense:2", "immersive_armors:steampunk_helmet defense:5", "immersive_armors:steampunk_chestplate defense:5", "immersive_armors:steampunk_leggings defense:6", "immersive_armors:steampunk_boots defense:6"]
#List of requirements to craft items.
#Format: mod:id skill:level
#Valid skills: attack, defense, mining, gathering, farming, building, agility, magic (plus any aliases defined in skillAliases)
craftSkillLocks = []
#List of requirements to attack entities.
#Format: mod:id skill:level
#Valid skills: attack, defense, mining, gathering, farming, building, agility, magic (plus any aliases defined in skillAliases)
attackSkillLocks = []
#List of substitutions to preform in names in skill lock lists.
#Useful if you're using a resource pack to change the names of skills, this config doesn't effect gameplay, just accepted values in other configs so its easier to think about
#Format: key=value
#Valid values: attack, defense, mining, gathering, farming, building, agility, magic
skillAliases = ["defense=defense"]

**Comment by Orangejewce92** [comment]
Unsure if related but I went to the original mod developers issue tracker and someone mentioned that they were only allowed to add 3 things at a time so it wouldn't crash? - this is ridiculous lol if you get a crash report with same issue please send crash report here so I can review the problem.

**Comment by Orangejewce92** [comment]
Please let me know if it fixed the issue ! Or any other issues open a new post

**Comment by Orangejewce92** [comment]
i've re-written the mod to have different areas for the configs to be done so you no longer get this error please update to version 3.0.0
