### ISSUE TITLE
Display bug skill locks

### ISSUE THREAD

**Issue by samji034p** [Orangejewce92/rereskillable#5]
When i add skill locks  on my server in the json file, i don't see the skill requirement on the item, but when i use it with insuffisant level, the mod works but i still don't see the skill requirement. If i modify existing one in the json file, the skill requirement is still the same.
The mod works but it has a display bug when i add or modify skill requirement for items

**Comment by Orangejewce92** [comment]
files have to match both client and server. the reload feature is meant for easy editing while in singleplayer.
I can look into a way to sync across client about it.

**Comment by Orangejewce92** [comment]
Closing ticket but i will look into it

**Comment by Orangejewce92** [comment]
Best way to do this is to change the location of the config to the serverconfig folder. I can do this but it would result in moving the config once more
