### ISSUE TITLE
Error during mod loading

### ISSUE THREAD

**Issue by HUAHU28** [Orangejewce92/rereskillable#6]
I have attached an image of the error and the crash log.

[crash-2024-07-27_01.55.55-fml.txt](https://github.com/user-attachments/files/16394009/crash-2024-07-27_01.55.55-fml.txt)
![Screenshot 2024-07-27 015743](https://github.com/user-attachments/assets/cbc3dd8a-81e6-4033-befa-804211b31e4f)

**Comment by Orangejewce92** [comment]
you need to update your config file. 
( delete the current one and regenerate new ones )
i fixed a typo in "defence" with the correct spelling defense
