### ISSUE TITLE
crash on launch 

### ISSUE THREAD

**Issue by tylerMakrush** [Orangejewce92/rereskillable#9]
i crash whenever i luanch even if this is the only mod i have i am not sure why 
[crash-2024-11-12_10.31.45-fml.txt](https://github.com/user-attachments/files/17718823/crash-2024-11-12_10.31.45-fml.txt)

**Comment by Orangejewce92** [comment]
any small error in the config will cause a crash.

	Mod File: /C:/Users/tyler/curseforge/minecraft/Instances/1.20/mods/rereskillable-3.0.8-1.20.1.jar
	Failure message: Rereskillable (rereskillable) encountered an error during the common_setup event phase
		java.lang.IllegalArgumentException: No enum constant majik.rereskillable.common.commands.skills.Skill.DEFENCE
	Mod Version: 3.0.8-1.20.1
	Mod Issue URL: NOT PROVIDED
	
	you can delete your config and try again
